all: exo1 exo2 exo3 exo4-2 exo5

exo1: annexe01.cpp
	g++ annexe01.cpp -std=c++17 -Wall -Wextra -o exo1

exo2: exo2.cpp
	g++ exo2.cpp -std=c++17 -Wall -Wextra -o exo2

exo3: exo3.cpp
	g++ exo3.cpp -std=c++17 -Wall -Wextra -o exo3

exo4-2: exo4-2.cpp
	g++ exo4-2.cpp -std=c++17 -Wall -Wextra -o exo4-2

exo5: exo5.cpp
	g++ exo5.cpp -std=c++17 -Wall -Wextra -o exo5




clean:
	rm exo1
	rm exo2
	rm exo3
	rm exo4-2
	rm exo5

