all: annexe1 annexe2

annexe1: annexe01_copy.cpp
	g++ annexe01_copy.cpp -std=c++17 -Wall -Wextra -o annexe1

annexe2: annexe02_copy.cpp
	g++ annexe02_copy.cpp -std=c++17 -Wall -Wextra -o annexe2


tp1:tp1.cpp
	g++ tp1.cpp -std=c++17 -Wall -Wextra -o tp1


clean:
	rm annexe1
	rm annexe2
	#rm tp1
